### ISSUE TITLE
Incompatibilty with Nothirium Mod

### ISSUE THREAD

**Issue by Celse2021** [lambda-client/lambda#382]
**What mod?**
Nothirium, a mod which updates OpenGL to newer versions like sodium, but for 1.12 or later (obviously its for forge) This mod uses a newer mixins version but has a compatibity mixins mod that should make work, but it doesnt.

**Logs**
No log generated but, got debug console open and got a crash log there:
[19:10:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:10:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:10:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:10:58] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[19:10:58] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-legacy\windows-x64\jre-legacy
[19:10:58] [main/INFO] [FML]: Searching C:\Users\celse\AppData\Roaming\.minecraft\mods for mods
[19:10:58] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from [___MixinCompat-0.8___].jar
[19:10:58] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from _MixinBootstrap-1.1.0.jar
[19:10:58] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from lambda-3.2.1.jar
[19:10:58] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Nothirium-1.12.2-0.1.9-beta.jar
[19:10:58] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_G5.jar
[19:10:58] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from RenderLib-1.12.2-1.1.9.jar
[19:10:58] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:10:58] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[19:10:58] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/celse/AppData/Roaming/.minecraft/mods/%5B___MixinCompat-0.8___%5D.jar Service=LaunchWrapper Env=CLIENT
[19:10:58] [main/WARN] [FML]: The coremod LambdaCoreMod (com.lambda.client.LambdaCoreMod) is not signed!
[19:10:58] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[19:10:58] [main/ERROR] [mixin]: Mixin config mixins.lambda.json does not specify "minVersion" property
[19:10:58] [main/ERROR] [mixin]: Mixin config mixins.baritone.json does not specify "minVersion" property
[19:10:59] [main/INFO] [Lambda]: Lambda and Baritone mixins initialised. (searge)
[19:10:59] [main/WARN] [FML]: The coremod NothiriumPlugin (meldexun.nothirium.mc.asm.NothiriumPlugin) is not signed!
[19:10:59] [main/WARN] [FML]: The coremod RenderLibPlugin (meldexun.renderlib.asm.RenderLibPlugin) is not signed!
[19:10:59] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[19:10:59] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[19:10:59] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[19:10:59] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[19:10:59] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[19:10:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:10:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:10:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:10:59] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[19:10:59] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[19:10:59] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[19:10:59] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[19:10:59] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\celse\AppData\Roaming\.minecraft\mods\OptiFine_1.12.2_HD_U_G5.jar
[19:10:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:11:02] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:11:02] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[19:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[19:11:02] [main/ERROR] [mixin]: Mixin config mixins.mixincompat.json does not specify "minVersion" property
[19:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:11:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:11:02] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:11:02] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:11:02] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[19:11:02] [main/WARN] [mixin]: Reference map 'mixins.mixincompat.refmap.json' for mixins.mixincompat.json could not be read. If this is a development environment you can ignore this message
[19:11:03] [main/INFO] [meldexun.asmutil.ASMUtil]: Transforming method: setWorldAndLoadRenderers net/minecraft/client/renderer/RenderGlobal
[19:11:03] [main/INFO] [meldexun.asmutil.ASMUtil]: Transforming method: loadRenderers net/minecraft/client/renderer/RenderGlobal
[19:11:03] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.meldexun.nothirium.mc.asm.NothiriumClassTransformer' was detected and will no longer process meta class data
[19:11:03] [main/INFO] [meldexun.asmutil.ASMUtil]: Transforming method: RenderGlobal#renderEntities(Entity, ICamera, float)
[19:11:04] [main/WARN] [mixin]: @Mixin target net/minecraft/block/state/BlockStateContainer$StateImplementation is public in mixins.baritone.json:MixinStateImplementation and should be specified in value
[19:11:04] [main/WARN] [mixin]: Error loading class: fionathemortal/betterbiomeblend/BiomeColor (java.lang.ClassNotFoundException: The specified class 'fionathemortal.betterbiomeblend.BiomeColor' was not found)
[19:11:04] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:11:04] [main/FATAL] [mixin]: Mixin apply failed mixins.baritone.json:MixinMinecraft -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field h was not located in the target class net.minecraft.client.Minecraft. Using refmap mixins.baritone.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field h was not located in the target class net.minecraft.client.Minecraft. Using refmap mixins.baritone.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:616) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:292) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) [%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [%5B___MixinCompat-0.8___%5D.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.client.main.Main.main(SourceFile:38) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.baritone.json:MixinMinecraft] from phase [DEFAULT] in config [mixins.baritone.json] FAILED during APPLY
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.client.main.Main.main(SourceFile:38)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:11:04] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field h was not located in the target class net.minecraft.client.Minecraft. Using refmap mixins.baritone.refmap.json
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:616)
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:292)
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267)
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271)
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[19:11:04] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 14 more
[19:11:04] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.baritone.json:MixinMinecraft] from phase [DEFAULT] in config [mixins.baritone.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field h was not located in the target class net.minecraft.client.Minecraft. Using refmap mixins.baritone.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:616) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:292) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[%5B___MixinCompat-0.8___%5D.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 6 more
[19:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[19:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[19:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[19:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:11:04] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Additional context**
I think its a problem with your client because in the logs, it says lambda.json does not specify ''min version'' property (refering to the mixins version lambda uses) which is a mixin compatibility thing. Mixins compatibility version is 0.7-0.8

**Comment by Celse2021** [comment]
You can close issue, problem was mixins compatibilty mod.
